version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - java -version

  build:
    commands:
      - cd AIVLE-4_mini_project-back/miniproject4-spring/miniproject04
      - chmod +x gradlew
      - ./gradlew clean build -x test

artifacts:
  files:
    - AIVLE-4_mini_project-back/miniproject4-spring/miniproject04/build/libs/*.jar